# Author:https://github.com/Repcz
# TG:https://t.me/QVQ_Channel
#
# å®˜æ–¹æ–‡æ¡£ï¼šhttps://wiki.metacubex.one/
#
# ä»¥ '#' æˆ– '//' å¼€å¤´çš„é…ç½®æ–‡ä»¶è¡Œä¸ºæ³¨é‡Šè¡Œ
#
# Mihomo Version â‰¥ 1.8.10
#
# æœ€åæ›´æ–°æ—¶é—´: 2025-02-13 22:10
#
# ================

p: &p {type: http, interval: 86400, health-check: {enable: true, url: http://1.1.1.1/generate_204, interval: 1800, timeout: 5000}}
proxy-providers:
  Subscribe: # åœ¨æ­¤å°† "http://your-service-provider" æ›¿æ¢ä¸ºä½ çš„æœºåœºè®¢é˜…ï¼Œæ¨èä½¿ç”¨ base64 æˆ–è€… node list
    url: http://your-service-provider
    <<: *p
    #override: # ä¿®æ”¹èŠ‚ç‚¹å‰åç¼€æ—¶ï¼Œéœ€ç§»é™¤å‰æ–¹çš„ "#" ç¬¦å·
      #additional-prefix: "èŠ‚ç‚¹å‰ç¼€"
      #additional-suffix: "èŠ‚ç‚¹åç¼€"
  #Subscribe2: {url: http://your-service-provider, <<: *p}
  #Subscribe3: {url: http://your-service-provider, <<: *p}
  #Subscribe4: {url: http://your-service-provider, <<: *p}

mixed-port: 7893
tcp-concurrent: true
allow-lan: true
ipv6: false
log-level: info
unified-delay: true
global-client-fingerprint: chrome
find-process-mode: strict

geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  asn: "https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb"

profile: { store-selected: true, store-fake-ip: false }
sniffer: { enable: true, sniff: { HTTP: { ports: [80], override-destination: true }, TLS: { ports: [443, 8443] }, QUIC: { ports: [443, 8443] } } }

tun:
  enable: true
  stack: mixed
  dns-hijack: [any:53]
        
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: :1053
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ['*', '+.lan', '+.local', '+.direct', '+.msftconnecttest.com', '+.msftncsi.com']
  nameserver: [223.5.5.5, 119.29.29.29]

# é”šç‚¹å‚æ•°
pg: &pg {type: select, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â­ ç‰¹æ®ŠèŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹]}
url-test: &url-test {type: url-test, url: http://1.1.1.1/generate_204, interval: 300, tolerance: 0, include-all: true}
select: &select {type: select, include-all: true}
fallback: &fallback {type: fallback, url: http://1.1.1.1/generate_204, interval: 300, include-all: true}
load-balance: &load-balance {type: load-balance, strategy: consistent-hashing, url: http://1.1.1.1/generate_204, interval: 300, include-all: true}
c: &c {type: http, behavior: classical, format: text, interval: 86400}

proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, include-all: true}
  - {name: â­ ç‰¹æ®ŠèŠ‚ç‚¹, type: select, include-all: true}
  - {name: ğŸ“½ï¸ EmbyæœåŠ¡, <<: *pg}
  - {name: â˜ äº‘ç›˜æœåŠ¡, <<: *pg}
  - {name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯, <<: *pg}
  - {name: ğŸ¦ æ¨ç‰¹æ¶ˆæ¯, <<: *pg}
  - {name: ğŸ¤– AIæœåŠ¡, <<: *pg}
  - {name: ğŸ® æ¸¸æˆå¹³å°, <<: *pg}
  - {name: ğŸ…± å“”å“©å“”å“©, <<: *pg}
  - {name: ğŸ“º å·´å“ˆå§†ç‰¹, <<: *pg}
  - {name: ğŸ‡¬ è°·æ­ŒæœåŠ¡, <<: *pg}
  - {name: ğŸ‡² å¾®è½¯æœåŠ¡, <<: *pg,}
  - {name: ğŸ‘˜ ä»…é™æ—¥æœ¬, <<: *pg}
  - {name: ğŸŸ å…œåº•åˆ†æµ, <<: *pg}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, <<: *url-test, filter: "(?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|Hong)\b)"}
  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, <<: *url-test, filter: "(?i)ğŸ‡¨ğŸ‡³|ğŸ‡¹ğŸ‡¼|å°æ¹¾|(\b(TW|Tai|Taiwan)\b)"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, <<: *url-test, filter: "(?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|ä¸œäº¬|(\b(JP|Japan)\b)"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, <<: *url-test, filter: "(?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®|(\b(SG|Singapore)\b)"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, <<: *url-test, filter: "(?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ´›æ‰çŸ¶|åœ£ä½•å¡|(\b(US|United States)\b)"}

rule-providers:
  Direct: {<<: *c, path: ./rules/Direct.list, url: https://github.com/Sofzya/Clash/raw/main/Rules/Direct.list}
  Emby: {<<: *c, path: ./rules/Emby.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Emby.list}
  CloudDrive: {<<: *c, path: ./rules/CloudDrive, url: https://github.com/Sofzya/Clash/raw/main/Rules/CloudDrive.list}
  MEGA: {<<: *c, path: ./rules/MEGA.list, url: https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/MEGA/MEGA.list}
  Telegram: {<<: *c, path: ./rules/Telegram.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Telegram.list}
  Twitter: {<<: *c, path: ./rules/Twitter.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Twitter.list}
  AI: {<<: *c, path: ./rules/AI.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/AI.list}
  Steam: {<<: *c, path: ./rules/Steam.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Steam.list}
  Epic: {<<: *c, path: ./rules/Epic.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Epic.list}
  BiliBili: {<<: *c, path: ./rules/Bilibili.list, url: https://github.com/Repcz/Tool/blob/X/Clash/Rules/Bilibili.list}
  Bahamut: {<<: *c, path: ./rules/Bahamut.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Bahamut.list}
  YouTube: {<<: *c, path: ./rules/YouTube.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/YouTube.list}
  Google: {<<: *c, path: ./rules/Google.list, url: https://github.com/Repcz/Tool/raw/X/Clash/Rules/Google.list}
  OnlyJP: {<<: *c, path: ./rules/OnlyJP, url: https://github.com/Sofzya/Clash/raw/main/Rules/OnlyJP.list}

rules:
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Emby,ğŸ“½ï¸ EmbyæœåŠ¡
  - RULE-SET,CloudDrive,â˜ äº‘ç›˜æœåŠ¡
  - RULE-SET,MEGA,â˜ äº‘ç›˜æœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,Twitter,ğŸ¦ æ¨ç‰¹æ¶ˆæ¯
  - RULE-SET,AI,ğŸ¤– AIæœåŠ¡
  - RULE-SET,Steam,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Epic,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,BiliBili,ğŸ…± å“”å“©å“”å“©
  - RULE-SET,Bahamut,ğŸ“º å·´å“ˆå§†ç‰¹
  - RULE-SET,YouTube,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - RULE-SET,Google,ğŸ‡¬ è°·æ­ŒæœåŠ¡
  - RULE-SET,OnlyJP,ğŸ‘˜ ä»…é™æ—¥æœ¬
  - GEOSITE,onedrive,ğŸ‡² å¾®è½¯æœåŠ¡
  - GEOSITE,github,ğŸ‡² å¾®è½¯æœåŠ¡
  - GEOSITE,microsoft,ğŸ‡² å¾®è½¯æœåŠ¡
  - GEOSITE,gfw,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,private,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,ğŸŸ å…œåº•åˆ†æµ
